### ISSUE TITLE
Black Screen

### ISSUE THREAD

**Issue by xTaiwanPingLord** [mighildotcom/X79-Hackintosh-Catalina#1] opened 2020-02-03 14:41 UTC
I am a Chinese. Sorry for bad English.
I have a New built PC and the specs are similar to yours:
E5 2650
Huanan X79-ZD3
DDR3 REG ECC 1600 8G x4
Sapphire RX570 4G
Micron MX500 500G
But when i created the USB drive and replaced the Clover's EFI file to yours, 
i got black screen and nothing going down. 
Caps lock and Num lock **works** but black screen.
I tried update the Whatevergreen and lilu kext - Still black screen
any ideas? thanks :D

**Comment by verfasor** [comment] 2020-02-04 04:21
The issue is unrelated to this repo since the hardware doesn’t match. So I’ll close it here & we can talk via email or Weixin. Please email your case and error log to webmaster@mighil.com. Weixin @mighil.

**Closed as completed** 2020-02-04 04:23 UTC
